spring:
  application:
    name: AImailbox
  datasource:
    url: jdbc:postgresql://ep-fragrant-frog-a1hl4rhq-pooler.ap-southeast-1.aws.neon.tech/neondb
    username: neondb_owner
    password: npg_cAuqvd5mMs1E
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  secret: nkjhuv3787v09nhfuehcn93784nvcjsd
  access-expiration-minutes: 15
  refresh-expiration-days: 7

google:
  client-id: 301820514600-0rql8nnidjflqicvojj1im9c7tkdmuus.apps.googleusercontent.com
  client-secret: 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
  redirect-uri: http://localhost:8080/auth/google/callback
  generative-api-key: AIzaSyBNtT0oTH7ZZxOxhdgpveA8nvPLtT0cr4o

# Frontend callback URL used by backend to redirect user after Google auth
frontend:
  #callback-url: http://localhost:5174/auth/google/callback
  callback-url: https://aimail-rdcdzbplk-vinhs-projects-373b8979.vercel.app/auth/google/callback

cors:
  # include deployed Vercel frontend plus local dev origins
  allowed-origins: https://aimail-7fc0kb7bb-vinhs-projects-373b8979.vercel.app,http://localhost:5173,http://localhost:5174,http://localhost:3000,https://aimail-fsze5u387-vinhs-projects-373b8979.vercel.app/,https://aimail-rdcdzbplk-vinhs-projects-373b8979.vercel.app/


