spring:
  application:
    name: AImailbox

jwt:
  secret: nkjhuv3787v09nhfuehcn93784nvcjsd
  access-expiration-minutes: 15
  refresh-expiration-days: 7

cors:
  allowed-origins: http://localhost:5173,http://localhost:3000

datasource:
  url: jdbc:h2:mem:testdb
  driverClassName: org.h2.Driver
  username: sa
  password:
jpa:
  hibernate:
    ddl-auto: update
  show-sql: false
